require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-i18n

AllCops:
  NewCops: enable

I18n/RailsI18n:
  Enabled: true
  Exclude:
    - spec/rails_helper.rb

I18n/GetText:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
