name: Ruby

on: [push]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_DB: xpense_tracker_api_test
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/xpense_tracker_api
  RAILS_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run Rubocop
        run: rubocop

  test:
    runs-on: ubuntu-latest
    name: Run tests with RSpec
    steps:
      - uses: actions/checkout@v2

      - name: Read .ruby-version
        id: nvm
        run: echo ::set-output name=RUBYVERSION::$(cat .ruby-version)
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ steps.nvm.outputs.RUBYVERSION }}'

      - name: Cache bundle
        uses: actions/cache@v1
        with:
          path: .bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          gem install bundler
          bundle config set path .bundle
          bundle install --jobs 4

      - name: Migrate database
        # env:
        #   DATABASE_URL: ${{ env.DATABASE_URL }}
        #   RAILS_ENV: ${{ env.RAILS_ENV }}
        run: |
          cp .env.example .env
          bin/rails db:setup

      - name: Run RSpec
        # env:
        #   DATABASE_URL: ${{ env.DATABASE_URL }}
        run: bin/rspec
