name: Ruby

on: [push, pull_request]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_DB: xpense_tracker_api_test
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/xpense_tracker_api
  RAILS_ENV: test

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bin/rubocop

      - name: Setup everything else
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          RAILS_ENV: ${{ env.RAILS_ENV }}
        run: bin/setup

      - name: Run tests with RSpec
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: bin/rspec
